#!/usr/bin/env python3
# Copyright (c) 2025 Siliscale Consulting, LLC
# SPDX-License-Identifier: Apache-2.0
"""Generate fpga/<board>/work/include/{global,hw_config}.svh from board.yaml + HW preset."""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

import yaml

_REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_REPO))

from hw.load import load_hw_config  # noqa: E402
from hw.rtl_config import write_hw_config_svh  # noqa: E402


def _write_global_svh(path: Path, iccm_depth: int, dccm_depth: int) -> None:
    text = f"""\
// Generated by fpga/*/scripts/gen_fpga_config.py — do not edit.
`ifndef GLOBAL_SVH
`define GLOBAL_SVH

localparam int XLEN = 32;
localparam int XLEN_BYTES = XLEN / 8;

localparam int RESET_VECTOR = 32'h00000000;

localparam int INSTR_LEN = 32;
localparam int INSTR_LEN_BYTES = INSTR_LEN / 8;

localparam int DATA_LEN = XLEN;
localparam int DATA_LEN_BYTES = DATA_LEN / 8;

localparam int INSTR_MEM_WIDTH = XLEN;
localparam int INSTR_MEM_DEPTH = {iccm_depth};
localparam int INSTR_MEM_ADDR_WIDTH = $clog2(INSTR_MEM_DEPTH * INSTR_MEM_WIDTH / 8);
localparam int INSTR_MEM_TAG_WIDTH = XLEN;

localparam int DATA_MEM_WIDTH = XLEN;
localparam int DATA_MEM_DEPTH = {dccm_depth};
localparam int DATA_MEM_ADDR_WIDTH = $clog2(DATA_MEM_DEPTH * DATA_MEM_WIDTH / 8);

localparam int REG_FILE_DEPTH = 32;
localparam int REG_FILE_ADDR_WIDTH = $clog2(REG_FILE_DEPTH);

`include "hw_config.svh"

`endif
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--board-dir", type=Path, required=True)
    ap.add_argument("--work-dir", type=Path, required=True)
    ap.add_argument(
        "--hw-config",
        type=Path,
        default=_REPO / "hw" / "presets" / "rv32im_scalar.yaml",
        help="Path to hw preset YAML",
    )
    args = ap.parse_args()

    board = yaml.safe_load((args.board_dir / "board.yaml").read_text(encoding="utf-8"))
    iccm = int(board.get("synth_iccm_depth_words", 4096))
    dccm = int(board.get("synth_dccm_depth_words", 4096))

    hw = load_hw_config(args.hw_config)
    out_inc = args.work_dir / "include"
    out_inc.mkdir(parents=True, exist_ok=True)

    _write_global_svh(out_inc / "global.svh", iccm, dccm)
    write_hw_config_svh(out_inc / "hw_config.svh", hw)

    # types / decode headers stay shared from rtl/include
    for name in ("types.svh", "mul_pd_config.svh"):
        src = _REPO / "rtl" / "include" / name
        if src.exists():
            shutil.copy2(src, out_inc / name)

    print(f"FPGA config: iccm={iccm} dccm={dccm} -> {out_inc}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
