// Generated by hw/scripts/gen_rtl_config.py — do not edit.
`ifndef HW_CONFIG_SVH
`define HW_CONFIG_SVH

localparam int EXU_COUNT = 1;

localparam int EXU_HAS_ALU[EXU_COUNT] = '{1};
localparam int EXU_HAS_MUL[EXU_COUNT] = '{1};
localparam int EXU_HAS_DIV[EXU_COUNT] = '{1};
localparam int EXU_HAS_LSU[EXU_COUNT] = '{1};

`endif
