// Generated by hw/scripts/gen_rtl_config.py — do not edit.
`ifndef HW_CONFIG_SVH
`define HW_CONFIG_SVH

localparam int ISSUE_WIDTH = 1;

enum logic [1:0] {
  VLIW = 2'b00,
  SUPERSCALAR = 2'b01,
  OOO = 2'b10
} PIPELINE_KIND = VLIW;

localparam int EXU_COUNT = 1;

localparam int EXU_HAS_ALU[EXU_COUNT] = '{1};
localparam int EXU_HAS_MUL[EXU_COUNT] = '{1};
localparam int EXU_HAS_DIV[EXU_COUNT] = '{1};
localparam int EXU_HAS_LSU[EXU_COUNT] = '{1};

localparam int LSU_LOAD_QUEUE_DEPTH  = 4;
localparam int LSU_STORE_QUEUE_DEPTH = 4;
localparam int LSU_DCCM_PORT_COUNT   = 1;

`endif
