# Copyright (c) 2025 Siliscale Consulting, LLC
# SPDX-License-Identifier: Apache-2.0

"""Lower an FX graph to a host-testable C program that calls PyVedas runtime ops."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Set, Tuple

import torch.fx as fx

from .codegen_handlers import CODEGEN_HANDLERS
from .memory import (
    BufferMaterializer,
    FlatRowMajorMaterializer,
    MemoryPlan,
    emit_static_buffers,
    format_shape,
)
from .registry import RegistryError, RuntimeOp, resolve_op, canonical_graph_target, _EXPORT_SKIP_TARGETS


@dataclass
class CompilePlan:
    memory: MemoryPlan
    statements: List[str]
    runtime_sources: List[Path]
    includes: List[str]
    # Output buffer name + flattened int goldens for target self-check (optional).
    result_name: str | None = None
    result_golden: Tuple[int, ...] = ()


def _buffer_name(node: fx.Node) -> str:
    return node.name.replace("%", "v_")


def _output_value(node: fx.Node) -> fx.Node:
    value = node.args[0]
    while isinstance(value, tuple):
        if len(value) != 1:
            raise RegistryError(f"Unsupported output shape: {node.args}")
        value = value[0]
    if not isinstance(value, fx.Node):
        raise RegistryError(f"Expected FX node in output, got {type(value)}")
    return value


def _bind_trace_inputs(
    placeholders: List[fx.Node],
    trace_inputs: Tuple[Any, ...],
    materializer: BufferMaterializer,
) -> MemoryPlan:
    if len(placeholders) != len(trace_inputs):
        raise RegistryError(
            f"Expected {len(placeholders)} trace inputs, got {len(trace_inputs)}"
        )

    memory = MemoryPlan()
    for node, trace_input in zip(placeholders, trace_inputs):
        buffer = materializer.materialize(_buffer_name(node), trace_input)
        memory.add(buffer)
    return memory


def lower_graph(
    graph: fx.Graph,
    registry: Dict[str, RuntimeOp],
    trace_inputs: Tuple[Any, ...],
    *,
    materializer: BufferMaterializer | None = None,
    gemm_scratch_bytes: int | None = None,
) -> CompilePlan:
    materializer = materializer or FlatRowMajorMaterializer()

    placeholders = [n for n in graph.nodes if n.op == "placeholder"]
    memory = _bind_trace_inputs(placeholders, trace_inputs, materializer)

    statements: List[str] = []
    runtime_sources: List[Path] = []
    seen_sources: Set[Path] = set()
    result_name: str | None = None

    for node in graph.nodes:
        if node.op == "placeholder":
            continue
        if node.op == "output":
            src = _buffer_name(_output_value(node))
            src_buf = memory.get(src)
            result_name = src
            statements.append(
                f"/* result buffer: {src} shape={format_shape(src_buf.shape)} */"
            )
            continue
        if node.op == "call_module":
            continue
        if node.op != "call_function":
            raise RegistryError(f"Unsupported FX node type: {node.op} ({node.name})")

        if canonical_graph_target(node.target) in _EXPORT_SKIP_TARGETS:
            continue

        op = resolve_op(registry, node.target)
        for src in op.sources:
            if src.path not in seen_sources:
                runtime_sources.append(src.path)
                seen_sources.add(src.path)

        handler = CODEGEN_HANDLERS.get(op.codegen)
        if handler is None:
            raise RegistryError(
                f"No codegen handler for '{op.graph_target}' "
                f"(codegen={op.codegen!r})"
            )

        statements.append(
            handler(
                op,
                node,
                memory,
                gemm_scratch_bytes=gemm_scratch_bytes,
            )
        )

    return CompilePlan(
        memory=memory,
        statements=statements,
        runtime_sources=runtime_sources,
        includes=["pyvedas.h"],
        result_name=result_name,
    )


def emit_c(plan: CompilePlan, out_path: Path, *, target: bool = False) -> None:
    lines: List[str] = [
        "/* Generated by PyVedas JIT. */",
        "#include <stddef.h>",
        "#include <stdint.h>",
    ]
    for header in plan.includes:
        lines.append(f"#include <{header}>")
    if not target:
        lines.append("#include <stdio.h>")
    if target:
        lines.append("")
        lines.append("extern void eot_sequence(void);")

    lines.append("")
    lines.extend(emit_static_buffers(plan.memory))

    lines.append("")
    lines.append("int main(void) {")
    if target:
        # -nostdlib has no CRT, so GP is otherwise 0 and linker-relaxed
        # addi(gp, ...) misses .data/.bss (broadcast/bmm scratch, C, goldens).
        lines.append("    asm volatile (")
        lines.append('        ".option push\\n"')
        lines.append('        ".option norelax\\n"')
        lines.append('        "la gp, __global_pointer$\\n"')
        lines.append('        ".option pop"')
        lines.append('        :')
        lines.append('        :')
        lines.append('        : "gp"')
        lines.append("    );")
    for stmt in plan.statements:
        for line in stmt.split("\n"):
            lines.append(f"    {line}" if line else "")

    if target:
        if plan.result_name and plan.result_golden:
            out_name = plan.result_name
            info = plan.memory.get(out_name)
            vals = ", ".join(str(v) for v in plan.result_golden)
            lines.append(
                f"    static const {info.c_type} _eot_golden[{info.numel}] = {{ {vals} }};"
            )
            lines.append(f"    for (size_t i = 0; i < {info.numel}; i++) {{")
            lines.append(f"        if ({out_name}[i] != _eot_golden[i]) {{")
            lines.append("            for (;;);")
            lines.append("        }")
            lines.append("    }")
        lines.append("    eot_sequence();")
    else:
        output_names = [
            b.name for b in plan.memory.buffers.values() if not b.is_initialized
        ]
        if output_names:
            out_name = output_names[-1]
            info = plan.memory.get(out_name)
            lines.append(f"    for (size_t i = 0; i < {info.numel}; i++) {{")
            lines.append(
                f'        printf("out[%zu]=%d\\n", i, (int){out_name}[i]);'
            )
            lines.append("    }")

    lines.append("    return 0;")
    lines.append("}")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
