# Copyright (c) 2025 Siliscale Consulting, LLC
# SPDX-License-Identifier: Apache-2.0
#
# Batch build for Alveo U280 QDMA + Tiny-Vedas SoC (Slice B).
# Usage: vivado -mode batch -source tcl/build.tcl -tclargs <board_dir> <work_dir>

if {$argc < 2} {
  puts "Usage: build.tcl <board_dir> <work_dir>"
  exit 1
}

set BOARD_DIR [file normalize [lindex $argv 0]]
set WORK_DIR  [file normalize [lindex $argv 1]]
set PART      xcu280-fsvh2892-2L-e
set PROJ      [file normalize [file join $BOARD_DIR ../..]]
set FPGA_INC  [file normalize [file join $WORK_DIR include]]

file mkdir $WORK_DIR
cd $WORK_DIR

# Config headers are generated by `make config` (system python) before Vivado —
# Vivado's PYTHONHOME breaks /usr/bin/python3.
set FPGA_INC [file normalize [file join $WORK_DIR include]]
if {![file exists [file join $FPGA_INC global.svh]]} {
  error "Missing $FPGA_INC/global.svh — run: make -C $BOARD_DIR config"
}

source [file join $BOARD_DIR tcl create_bd.tcl]

create_project tiny_vedas_u280 $WORK_DIR/vivado -part $PART -force
set_property target_language Verilog [current_project]

# Include path: FPGA-generated globals first
set_property include_dirs [list $FPGA_INC [file join $PROJ rtl include] [file join $PROJ rtl idu]] \
  [current_fileset]
set_property verilog_define [list SYNTHESIS] [current_fileset]

# Add Tiny-Vedas + SoC RTL (expand flist)
set flist [file join $BOARD_DIR rtl vedas_fpga.flist]
set fh [open $flist r]
set rtl_files {}
while {[gets $fh line] >= 0} {
  set line [string trim $line]
  if {$line eq "" || [string match "#*" $line]} { continue }
  set line [string map [list \$PROJ $PROJ \$FPGA_INC $FPGA_INC \$BOARD_DIR $BOARD_DIR] $line]
  if {![file exists $line]} {
    error "Missing RTL file from flist: $line"
  }
  # Headers are include-only; skip adding .svh as sources where possible
  if {[string match "*.svh" $line]} { continue }
  lappend rtl_files $line
}
close $fh
add_files -norecurse $rtl_files
set hdr_files [glob -nocomplain \
  [file join $FPGA_INC *.svh] \
  [file join $PROJ rtl include *.svh] \
  [file join $PROJ rtl idu *.svh]]
if {[llength $hdr_files] > 0} {
  add_files -norecurse $hdr_files
}
foreach f [concat $rtl_files $hdr_files] {
  if {[string match "*decode_out_t.svh" $f]} {
    # Compile as SV unit so typedef is in $unit (decoder has no `include).
    set_property file_type SystemVerilog [get_files $f]
  } elseif {[string match "*.sv" $f]} {
    set_property file_type SystemVerilog [get_files $f]
  } elseif {[string match "*.svh" $f]} {
    set_property file_type {Verilog Header} [get_files $f]
  }
}
# Force decode_out_t before decoder in compile order
set dec_h [get_files -quiet */decode_out_t.svh]
set dec_m [get_files -quiet */rv32im_decoder.sv]
if {$dec_h ne "" && $dec_m ne ""} {
  reorder_files -fileset sources_1 -before $dec_m $dec_h
}
update_compile_order -fileset sources_1

tv_create_pcie_bd

set xdc_files [glob -nocomplain $BOARD_DIR/constr/*.xdc]
if {[llength $xdc_files] == 0} {
  error "No XDC files found in $BOARD_DIR/constr"
}
add_files -fileset constrs_1 -norecurse $xdc_files

# CDC false paths need clocks present — apply at opt_design (not in XDC; 'if' illegal there)
set cdc_tcl $BOARD_DIR/constr/timing_cdc.tcl
add_files -fileset utils_1 -norecurse $cdc_tcl
set_property STEPS.OPT_DESIGN.TCL.PRE $cdc_tcl [get_runs impl_1]

set_property STEPS.WRITE_BITSTREAM.ARGS.BIN_FILE false [get_runs impl_1]

launch_runs synth_1 -jobs [exec nproc]
wait_on_run synth_1
if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
  error "Synthesis failed — see $WORK_DIR/vivado/*.runs/synth_1"
}

launch_runs impl_1 -to_step write_bitstream -jobs [exec nproc]
wait_on_run impl_1
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
  error "Implementation failed — see $WORK_DIR/vivado/*.runs/impl_1"
}

# --- Sign-off checks (fail before claiming success) ---
set impl_log [lindex [glob -nocomplain $WORK_DIR/vivado/*.runs/impl_1/runme.log] 0]
if {$impl_log eq "" || ![file exists $impl_log]} {
  error "Missing impl_1/runme.log"
}
set fh [open $impl_log r]
set logdata [read $fh]
close $fh
if {![regexp {TIMING_CDC: OK} $logdata]} {
  error "TIMING_CDC did not apply during opt_design — see $impl_log"
}

set twr [glob -nocomplain $WORK_DIR/vivado/*.runs/impl_1/*timing_summary_routed.rpt]
if {[llength $twr] == 0} {
  error "No routed timing summary"
}
file copy -force [lindex $twr 0] $WORK_DIR/timing_summary_routed.rpt
puts "TIMING_RPT: $WORK_DIR/timing_summary_routed.rpt"

set fh [open $WORK_DIR/timing_summary_routed.rpt r]
set rpt [read $fh]
close $fh

# CDC must not remain a failing inter-clock path
if {[regexp {clk_out1_pcie_bd_clk_wiz_0_0\s+axi_bram_ctrl_mm_BRAM_PORTA_CLK\s+-[0-9]} $rpt]} {
  error "CDC still failing (clk_out1 -> axi) — false_path did not take"
}

# Intra-clock WNS for core (Clock Summary lines use {duty} not a bare float after the name)
if {![regexp {clk_out1_pcie_bd_clk_wiz_0_0\s+(-?[0-9]+\.[0-9]+)\s+(-?[0-9]+\.[0-9]+)} $rpt -> core_wns core_tns]} {
  error "Could not parse core clk_out1 WNS from timing report"
}
if {$core_wns < 0} {
  error "Core 100 MHz timing failed: clk_out1 WNS=$core_wns ns"
}
puts "TIMING_OK: core_clk WNS=${core_wns} ns TNS=${core_tns} ns (CDC waived)"

set bit [glob -nocomplain $WORK_DIR/vivado/*.runs/impl_1/*.bit]
if {[llength $bit] == 0} {
  error "No bitstream produced"
}
file copy -force [lindex $bit 0] $WORK_DIR/tiny_vedas_u280.bit
puts "BITSTREAM: $WORK_DIR/tiny_vedas_u280.bit"
exit 0
