# Copyright (c) 2025 Siliscale Consulting, LLC
# SPDX-License-Identifier: Apache-2.0

"""Generate RTL configuration headers from :class:`HwConfig`."""

from __future__ import annotations

from pathlib import Path

from .types import ExuUnitMask, HwConfig


def _sv_int(value: bool) -> str:
    return "1" if value else "0"


def _sv_array(values: list[bool]) -> str:
    return "'{" + ", ".join(_sv_int(v) for v in values) + "}"


def render_hw_config_svh(hw: HwConfig) -> str:
    exu_units: list[ExuUnitMask] = list(hw.cpu.exu)
    exu_count = len(exu_units)

    return f"""\
// Generated by hw/scripts/gen_rtl_config.py — do not edit.
`ifndef HW_CONFIG_SVH
`define HW_CONFIG_SVH

localparam int EXU_COUNT = {exu_count};

localparam int EXU_HAS_ALU[EXU_COUNT] = {_sv_array([u.alu for u in exu_units])};
localparam int EXU_HAS_MUL[EXU_COUNT] = {_sv_array([u.mul for u in exu_units])};
localparam int EXU_HAS_DIV[EXU_COUNT] = {_sv_array([u.div for u in exu_units])};
localparam int EXU_HAS_LSU[EXU_COUNT] = {_sv_array([u.lsu for u in exu_units])};

`endif
"""


def write_hw_config_svh(path: Path | str, hw: HwConfig) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_hw_config_svh(hw), encoding="utf-8")
