# Copyright (c) 2025 Siliscale Consulting, LLC
# SPDX-License-Identifier: Apache-2.0

"""Generate SoC MMIO map artifacts (RTL header + software defines) from YAML."""

from __future__ import annotations

from pathlib import Path

from .load import repo_root
from .types import HwConfig, MmioDevice, SocConfig


def _rel_source(path: str) -> str:
    src = Path(path)
    try:
        return src.resolve().relative_to(repo_root()).as_posix()
    except ValueError:
        return src.name


def _sv_hex(value: int) -> str:
    return f"32'h{value & 0xFFFFFFFF:08X}"


def _c_hex(value: int) -> str:
    return f"0x{value & 0xFFFFFFFF:08X}"


def _asm_hex(value: int) -> str:
    return f"0x{value & 0xFFFFFFFF:08X}"


def _idx_name(dev: MmioDevice) -> str:
    return f"MMIO_IDX_{dev.name.upper()}"


def render_mmio_map_svh(soc: SocConfig) -> str:
    n = len(soc.devices)
    bases = ", ".join(_sv_hex(d.base) for d in soc.devices)
    sizes = ", ".join(_sv_hex(d.size) for d in soc.devices)

    idx_lines = "\n".join(
        f"localparam int {_idx_name(d)} = {i};" for i, d in enumerate(soc.devices)
    )
    named_lines = []
    for d in soc.devices:
        named_lines.append(f"localparam logic [31:0] {d.addr_macro} = {_sv_hex(d.base)};")
        named_lines.append(f"localparam logic [31:0] {d.size_macro} = {_sv_hex(d.size)};")
        if d.magic_macro is not None:
            magic = int(d.params["magic"]) & 0xFFFFFFFF
            named_lines.append(
                f"localparam logic [31:0] {d.magic_macro} = {_sv_hex(magic)};"
            )
    named = "\n".join(named_lines)

    return f"""\
// Generated by hw/scripts/gen_soc.py — do not edit.
// Source: {_rel_source(soc.source_path)}
`ifndef MMIO_MAP_SVH
`define MMIO_MAP_SVH

localparam int MMIO_DEV_COUNT = {n};

{idx_lines}

localparam logic [31:0] MMIO_DEV_BASE [MMIO_DEV_COUNT] = '{{{bases}}};
localparam logic [31:0] MMIO_DEV_SIZE [MMIO_DEV_COUNT] = '{{{sizes}}};

{named}

`endif
"""


def render_soc_defines_h(hw: HwConfig) -> str:
    soc = hw.soc
    lines = [
        f"#define SOC_NAME           \"{soc.name}\"",
        f"#define SOC_LINK_ADDRESS   {_c_hex(hw.memory.link_address)}",
        "",
    ]
    for d in soc.devices:
        lines.append(f"/* {d.name}: {d.compatible} @ {_c_hex(d.base)} size {d.size} */")
        lines.append(f"#define {d.addr_macro}   {_c_hex(d.base)}")
        lines.append(f"#define {d.size_macro}   {_c_hex(d.size)}")
        if d.magic_macro is not None:
            magic = int(d.params["magic"]) & 0xFFFFFFFF
            lines.append(f"#define {d.magic_macro}          {_c_hex(magic)}")
        lines.append("")
    body = "\n".join(lines).rstrip() + "\n"
    return f"""\
/* Generated by hw/scripts/gen_soc.py — do not edit. */
/* Source: {_rel_source(soc.source_path)} */
#ifndef SOC_DEFINES_H
#define SOC_DEFINES_H

{body}
#endif /* SOC_DEFINES_H */
"""


def render_soc_defines_inc(hw: HwConfig) -> str:
    """Gas `.include` view of the same map (used by `.s` tests)."""
    soc = hw.soc
    lines = [
        f"/* Generated by hw/scripts/gen_soc.py — do not edit. */",
        f"/* Source: {_rel_source(soc.source_path)} */",
        ".ifndef SOC_DEFINES_INC",
        ".set SOC_DEFINES_INC, 1",
        f".equ SOC_LINK_ADDRESS, {_asm_hex(hw.memory.link_address)}",
    ]
    for d in soc.devices:
        lines.append(f".equ {d.addr_macro}, {_asm_hex(d.base)}")
        lines.append(f".equ {d.size_macro}, {_asm_hex(d.size)}")
        if d.magic_macro is not None:
            magic = int(d.params["magic"]) & 0xFFFFFFFF
            lines.append(f".equ {d.magic_macro}, {_asm_hex(magic)}")
    lines.append(".endif")
    lines.append("")
    return "\n".join(lines)


def write_soc_artifacts(
    hw: HwConfig,
    *,
    mmio_svh: Path | str,
    soc_h: Path | str,
    soc_inc: Path | str,
) -> None:
    for path, text in (
        (Path(mmio_svh), render_mmio_map_svh(hw.soc)),
        (Path(soc_h), render_soc_defines_h(hw)),
        (Path(soc_inc), render_soc_defines_inc(hw)),
    ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
