#!/usr/bin/env python3
# Copyright (c) 2025 Siliscale Consulting, LLC
# SPDX-License-Identifier: Apache-2.0
"""Generate pd/active.mk, pd/include/global.svh, and pd/work/orfs_config.mk."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

_REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO))

from hw.load import load_hw_config  # noqa: E402

DEFAULT_PD_PLATFORM = "asap7"


def _write_global_svh(path: Path, iccm_depth: int, dccm_depth: int) -> None:
    text = f"""\
// Generated by pd/scripts/gen_active_config.py — do not edit.
`ifndef GLOBAL_SVH
`define GLOBAL_SVH

localparam int XLEN = 32;
localparam int XLEN_BYTES = XLEN / 8;

localparam int RESET_VECTOR = 32'h00000000;

localparam int INSTR_LEN = 32;
localparam int INSTR_LEN_BYTES = INSTR_LEN / 8;

localparam int DATA_LEN = XLEN;
localparam int DATA_LEN_BYTES = DATA_LEN / 8;

localparam int INSTR_MEM_WIDTH = XLEN;
localparam int INSTR_MEM_DEPTH = {iccm_depth};
localparam int INSTR_MEM_ADDR_WIDTH = $clog2(INSTR_MEM_DEPTH * INSTR_MEM_WIDTH / 8);
localparam int INSTR_MEM_TAG_WIDTH = XLEN;

localparam int DATA_MEM_WIDTH = XLEN;
localparam int DATA_MEM_DEPTH = {dccm_depth};
localparam int DATA_MEM_ADDR_WIDTH = $clog2(DATA_MEM_DEPTH * DATA_MEM_WIDTH / 8);

localparam int REG_FILE_DEPTH = 32;
localparam int REG_FILE_ADDR_WIDTH = $clog2(REG_FILE_DEPTH);

`endif
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _render_sdc(template: str, clock_period: float, clock_io_pct: float) -> str:
    period_text = (
        str(int(clock_period))
        if clock_period == int(clock_period)
        else str(clock_period)
    )
    io_text = (
        str(clock_io_pct)
        if clock_io_pct != int(clock_io_pct)
        else str(int(clock_io_pct))
    )
    return (
        template.replace("__CLK_PERIOD__", period_text).replace(
            "__CLK_IO_PCT__", io_text
        )
    )


def _resolve_clock(plat: dict) -> tuple[float, str, float | None]:
    """Return (period, unit, target_ghz_or_none)."""
    clock_unit = str(plat.get("clock_period_unit", "ns"))
    target_ghz = plat.get("target_clock_ghz")
    if target_ghz is not None:
        ghz = float(target_ghz)
        if clock_unit == "ps":
            period = 1000.0 / ghz
        elif clock_unit == "ns":
            period = 1.0 / ghz
        else:
            raise ValueError(f"unsupported clock_period_unit: {clock_unit}")
        return period, clock_unit, ghz

    period = float(
        plat.get(
            "clock_period",
            plat.get("clock_period_ns", 10.0),
        )
    )
    return period, clock_unit, None


def _orfs_config_lines(
    platform: str,
    verilog_out: Path,
    sdc_file: Path,
    core_util: int,
    place_addon: float,
    core_margin: int | None,
    orfs_exports: dict,
) -> str:
    lines = [
        "# Generated ORFS design config for Tiny-Vedas.",
        "export DESIGN_NICKNAME = tiny_vedas",
        "export DESIGN_NAME = core_top",
        f"export PLATFORM = {platform}",
        "",
        f"export VERILOG_FILES = {verilog_out}",
        f"export SDC_FILE = {sdc_file}",
        "",
        f"export CORE_UTILIZATION = {core_util}",
        f"export PLACE_DENSITY_LB_ADDON = {place_addon}",
    ]
    if core_margin is not None:
        lines.append(f"export CORE_MARGIN = {core_margin}")
    lines.extend(
        [
            "",
            "# sv2v emits Verilog-2005; ORFS slang frontend ingests it reliably.",
            "export SYNTH_HDL_FRONTEND = slang",
            "export SYNTH_SLANG_ARGS += -D SYNTHESIS",
        ]
    )
    for key, value in orfs_exports.items():
        lines.append(f"export {key} = {value}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--hw",
        default=str(_REPO / "hw" / "presets" / "rv32im_scalar.yaml"),
        help="Hardware preset YAML (CPU flavor)",
    )
    parser.add_argument(
        "--platform",
        default=DEFAULT_PD_PLATFORM,
        help="PD platform name under pd/platforms/",
    )
    args = parser.parse_args()

    hw = load_hw_config(args.hw)
    if hw.cpu.kind.value != "scalar":
        print(
            f"error: PD flow currently supports scalar RTL only; "
            f"preset '{hw.name}' is {hw.cpu.kind.value}",
            file=sys.stderr,
        )
        return 1

    platform_path = _REPO / "pd" / "platforms" / f"{args.platform}.yaml"
    if not platform_path.exists():
        print(f"error: unknown PD platform {platform_path}", file=sys.stderr)
        return 1

    with open(platform_path, "r", encoding="utf-8") as f:
        plat = yaml.safe_load(f) or {}

    iccm = int(plat.get("synth_iccm_depth_words", 1024))
    dccm = int(plat.get("synth_dccm_depth_words", 1024))
    orfs_root = Path(str(plat.get("orfs_root", "/tools/OpenROAD-flow-scripts")))
    sv2v = Path(str(plat.get("sv2v", "/tools/sv2v/bin/sv2v")))

    clock_period, clock_unit, target_ghz = _resolve_clock(plat)
    clock_io_pct = float(plat.get("clock_io_pct", 0.20))
    core_util = int(plat.get("core_utilization", 45))
    place_addon = float(plat.get("place_density_lb_addon", 0.15))
    core_margin = plat.get("core_margin")
    core_margin_int = int(core_margin) if core_margin is not None else None
    orfs_exports = plat.get("orfs_exports") or {}

    pd_dir = _REPO / "pd"
    work_dir = pd_dir / "work"
    work_dir.mkdir(parents=True, exist_ok=True)

    _write_global_svh(pd_dir / "include" / "global.svh", iccm, dccm)

    mul_config_src = _REPO / "rtl" / "include" / "mul_pd_config.svh"
    mul_config_dst = pd_dir / "include" / "mul_pd_config.svh"
    mul_config_dst.write_text(mul_config_src.read_text(encoding="utf-8"), encoding="utf-8")

    verilog_out = work_dir / "sv2v" / "tiny_vedas.v"
    sdc_template_path = pd_dir / "orfs" / args.platform / "tiny_vedas" / "constraint.sdc"
    if not sdc_template_path.exists():
        print(f"error: missing SDC template {sdc_template_path}", file=sys.stderr)
        return 1

    sdc_file = work_dir / f"constraint_{args.platform}.sdc"
    sdc_text = _render_sdc(
        sdc_template_path.read_text(encoding="utf-8"),
        clock_period,
        clock_io_pct,
    )
    sdc_file.write_text(sdc_text, encoding="utf-8")

    active_mk = pd_dir / "active.mk"
    active_mk.write_text(
        f"""\
# Generated by pd/scripts/gen_active_config.py — do not edit.
export TINY_VEDAS_ROOT="{_REPO}"
export HW_CONFIG="{Path(args.hw).resolve()}"
export HW_PRESET="{hw.name}"
export PD_PLATFORM="{args.platform}"
export ORFS_ROOT="{orfs_root}"
export SV2V="{sv2v}"
export PD_VERILOG="{verilog_out}"
export PD_SDC="{sdc_file}"
export PD_TOP="core_top"
export PD_CLOCK_PERIOD="{clock_period}"
export PD_CLOCK_PERIOD_UNIT="{clock_unit}"
export PD_TARGET_CLOCK_GHZ="{target_ghz if target_ghz is not None else ""}"
""",
        encoding="utf-8",
    )

    orfs_config = work_dir / "orfs_config.mk"
    orfs_config.write_text(
        _orfs_config_lines(
            args.platform,
            verilog_out,
            sdc_file,
            core_util,
            place_addon,
            core_margin_int,
            orfs_exports,
        ),
        encoding="utf-8",
    )

    print(f"HW preset:     {hw.name} ({hw.cpu.kind.value})")
    print(f"PD platform:   {args.platform}")
    if target_ghz is not None:
        print(f"Clock target:  {target_ghz:g} GHz ({clock_period:g} {clock_unit})")
    else:
        print(f"Clock target:  {clock_period:g} {clock_unit}")
    print(f"Synth memories: ICCM={iccm} DCCM={dccm} words")
    print(f"Wrote: {active_mk}")
    print(f"Wrote: {orfs_config}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
