#!/usr/bin/env python3
# Copyright (c) 2025 Siliscale Consulting, LLC
# SPDX-License-Identifier: Apache-2.0
"""Sweep legal single-flop mul pipeline placements (parallel ASAP7 rtl2gds)."""

from __future__ import annotations

import argparse
import csv
import os
import re
import subprocess
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
_SWEEP_ROOT = _REPO / "pd" / "work" / "sweep"
_ORFS_ROOT_DEFAULT = Path("/tools/OpenROAD-flow-scripts")


@dataclass(frozen=True)
class MulConfig:
    label: str
    booth: int = 0
    lr1: int = 0
    lr2: int = 0
    lr3: int = 0
    cpa: int = 1

    @property
    def nickname(self) -> str:
        safe = re.sub(r"[^a-z0-9_]+", "_", self.label.lower())
        return f"tiny_vedas_{safe}"

    def internal_stages(self) -> int:
        stages = self.booth + self.lr1 + self.lr2 + self.lr3
        if self.cpa > 1:
            stages += 1
        return stages

    def validate(self) -> None:
        if self.internal_stages() > 1:
            raise ValueError(f"{self.label}: more than one internal pipe stage")
        if self.cpa not in (1, 2):
            raise ValueError(f"{self.label}: PIPE_STAGES_CPA must be 1 or 2")


def _parse_finish_report(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    out: dict[str, object] = {}

    if m := re.search(r"fmax =\s+([-\d.]+)", text):
        out["fmax_mhz"] = float(m.group(1))
    if m := re.search(r"period_min =\s+([-\d.]+)", text):
        out["min_period_ps"] = float(m.group(1))
    if m := re.search(r"wns max\s+([-\d.]+)", text):
        out["wns_ps"] = float(m.group(1))

    max_section = re.search(
        r"finish report_checks -path_delay max\n-+\n(.*?\n\n\n)",
        text,
        re.DOTALL,
    )
    if max_section:
        block = max_section.group(1)
        if m := re.search(r"Startpoint:\s*(.+)", block):
            out["crit_start"] = m.group(1).strip()
        if m := re.search(r"Endpoint:\s*(.+)", block):
            out["crit_end"] = m.group(1).strip()
        if m := re.search(r"^\s+([-\d.]+)\s+slack \((MET|VIOLATED)\)", block, re.MULTILINE):
            out["crit_slack_ps"] = float(m.group(1))

    start = str(out.get("crit_start", ""))
    out["mul_critical"] = "exu_mul" in start or "booth_mul" in start
    return out


def _write_mul_config(path: Path, cfg: MulConfig) -> None:
    text = f"""\
// Generated by pd/scripts/sweep_mul_pipeline.py — do not edit.
`define MUL_PIPE_STAGE_AFTER_BOOTH {cfg.booth}
`define MUL_PIPE_STAGE_CSA_LR1 {cfg.lr1}
`define MUL_PIPE_STAGE_CSA_LR2 {cfg.lr2}
`define MUL_PIPE_STAGE_CSA_LR3 {cfg.lr3}
`define MUL_PIPE_STAGE_CSA_LR4 0
`define MUL_PIPE_STAGES_CPA {cfg.cpa}
"""
    path.write_text(text, encoding="utf-8")


def _write_orfs_config(
    path: Path,
    cfg: MulConfig,
    template: str,
    verilog: Path,
    sdc: Path,
) -> None:
    lines: list[str] = []
    for line in template.splitlines():
        if line.startswith("export DESIGN_NICKNAME"):
            lines.append(f"export DESIGN_NICKNAME = {cfg.nickname}")
        elif line.startswith("export VERILOG_FILES"):
            lines.append(f"export VERILOG_FILES = {verilog}")
        elif line.startswith("export SDC_FILE"):
            lines.append(f"export SDC_FILE = {sdc}")
        else:
            lines.append(line)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _run_sv2v(
    repo: Path,
    sv2v: Path,
    include_dirs: list[Path],
    verilog_out: Path,
    log: Path,
) -> None:
    sources: list[str] = []
    flist = repo / "pd" / "synth.flist"
    for raw in flist.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        sources.append(line.replace("$PROJ", str(repo)))

    inc_args: list[str] = []
    for inc in include_dirs:
        inc_args.extend(["-I", str(inc)])

    cmd = [
        str(sv2v),
        *inc_args,
        "--top=core_top",
        f"--write={verilog_out}",
        *sources,
    ]
    with log.open("a", encoding="utf-8") as lf:
        lf.write(f"==> sv2v -> {verilog_out}\n")
        lf.write(" ".join(cmd) + "\n")
        subprocess.run(cmd, cwd=repo, check=True, stdout=lf, stderr=subprocess.STDOUT)


def _run_orfs(orfs_root: Path, orfs_config: Path, log: Path) -> None:
    env_script = orfs_root / "env.sh"
    flow_dir = orfs_root / "flow"
    cmd = f"""
set -euo pipefail
source "{env_script}"
make -C "{flow_dir}" DESIGN_CONFIG="{orfs_config}"
"""
    with log.open("a", encoding="utf-8") as lf:
        lf.write("==> OpenROAD-flow-scripts\n")
        subprocess.run(
            ["bash", "-lc", cmd],
            check=True,
            stdout=lf,
            stderr=subprocess.STDOUT,
        )


def _run_one_sweep(args: tuple) -> dict[str, object]:
    """Worker entry point (must be top-level for multiprocessing)."""
    cfg_dict, repo_str, orfs_root_str, sv2v_str, sdc_str, template = args
    cfg = MulConfig(**cfg_dict)
    cfg.validate()

    repo = Path(repo_str)
    orfs_root = Path(orfs_root_str)
    sv2v = Path(sv2v_str)
    sdc = Path(sdc_str)

    sweep_dir = _SWEEP_ROOT / cfg.label
    sweep_dir.mkdir(parents=True, exist_ok=True)
    log = sweep_dir / "run.log"
    log.write_text(f"=== {cfg.label} ===\n", encoding="utf-8")

    t0 = time.time()
    _write_mul_config(sweep_dir / "mul_pd_config.svh", cfg)

    verilog_out = sweep_dir / "tiny_vedas.v"
    orfs_config = sweep_dir / "orfs_config.mk"
    _write_orfs_config(orfs_config, cfg, template, verilog_out, sdc)

    include_dirs = [
        sweep_dir,
        repo / "pd" / "include",
        repo / "rtl" / "include",
        repo / "rtl" / "idu",
    ]
    _run_sv2v(repo, sv2v, include_dirs, verilog_out, log)
    _run_orfs(orfs_root, orfs_config, log)

    finish_rpt = (
        orfs_root
        / "flow"
        / "reports"
        / "asap7"
        / cfg.nickname
        / "base"
        / "6_finish.rpt"
    )
    if not finish_rpt.is_file():
        raise FileNotFoundError(f"missing finish report: {finish_rpt}")

    metrics = _parse_finish_report(finish_rpt)
    return {
        "label": cfg.label,
        "design_nickname": cfg.nickname,
        "booth": cfg.booth,
        "lr1": cfg.lr1,
        "lr2": cfg.lr2,
        "lr3": cfg.lr3,
        "cpa": cfg.cpa,
        "internal_stages": cfg.internal_stages(),
        "elapsed_s": round(time.time() - t0, 1),
        "finish_report": str(finish_rpt),
        "log": str(log),
        **metrics,
    }


def _candidate_configs() -> list[MulConfig]:
    return [
        MulConfig("baseline"),
        MulConfig("after_booth", booth=1),
        MulConfig("after_csa_lr1", lr1=1),
        MulConfig("after_csa_lr2", lr2=1),
        MulConfig("after_csa_lr3", lr3=1),
        MulConfig("cpa_2lane", cpa=2),
    ]


def _load_active_mk() -> dict[str, str]:
    active = _REPO / "pd" / "active.mk"
    if not active.is_file():
        raise FileNotFoundError(f"{active} missing — run 'make config' first")
    env: dict[str, str] = {}
    for line in active.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line.startswith("export "):
            continue
        key, _, value = line.removeprefix("export ").partition("=")
        env[key.strip()] = value.strip().strip('"')
    return env


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=_REPO / "pd" / "work" / "mul_sweep_results.csv",
    )
    parser.add_argument(
        "-j",
        "--jobs",
        type=int,
        default=min(len(_candidate_configs()), os.cpu_count() or 1),
        help="Parallel PD jobs (default: min(configs, CPU count))",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print configs only; do not run PD",
    )
    args = parser.parse_args()

    cfgs = _candidate_configs()
    if args.dry_run:
        for cfg in cfgs:
            print(
                f"{cfg.label:16} nickname={cfg.nickname:28} "
                f"internal_stages={cfg.internal_stages()} cpa={cfg.cpa}"
            )
        return 0

    subprocess.run(["make", "config"], cwd=_REPO, check=True)
    active = _load_active_mk()
    orfs_template = (_REPO / "pd" / "work" / "orfs_config.mk").read_text(encoding="utf-8")
    sdc = Path(active["PD_SDC"])
    sv2v = Path(active["SV2V"])
    orfs_root = Path(active.get("ORFS_ROOT", str(_ORFS_ROOT_DEFAULT)))

    jobs = max(1, min(args.jobs, len(cfgs)))
    print(
        f"Sweeping {len(cfgs)} legal mul configs with -j {jobs} "
        f"(isolated ORFS nicknames under pd/work/sweep/<label>/).\n"
        "Note: non-baseline configs need exu_mul e2/e3 realignment for functional correctness."
    )

    worker_args = [
        (
            {
                "label": c.label,
                "booth": c.booth,
                "lr1": c.lr1,
                "lr2": c.lr2,
                "lr3": c.lr3,
                "cpa": c.cpa,
            },
            str(_REPO),
            str(orfs_root),
            str(sv2v),
            str(sdc),
            orfs_template,
        )
        for c in cfgs
    ]

    rows: list[dict[str, object]] = []
    errors: list[str] = []
    t0 = time.time()

    with ProcessPoolExecutor(max_workers=jobs) as pool:
        futures = {pool.submit(_run_one_sweep, wa): wa[0]["label"] for wa in worker_args}
        for fut in as_completed(futures):
            label = futures[fut]
            try:
                row = fut.result()
                rows.append(row)
                print(
                    f"[done] {label:16} Fmax={row.get('fmax_mhz')} MHz  "
                    f"mul_critical={row.get('mul_critical')}  "
                    f"({row.get('elapsed_s')}s)"
                )
            except Exception as exc:  # noqa: BLE001 — collect all worker failures
                errors.append(f"{label}: {exc}")
                print(f"[fail] {label}: {exc}", file=sys.stderr)

    rows.sort(key=lambda r: str(r["label"]))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if rows:
        fieldnames = list(rows[0].keys())
        with args.output.open("w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)

    print(f"\nWall time: {time.time() - t0:.1f}s  results: {args.output}")

    if errors:
        print("\nFailures:", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        return 1

    if not rows:
        return 1

    best = max(rows, key=lambda r: float(r.get("fmax_mhz", 0)))
    print("\n=== Best Fmax ===")
    print(f"  {best['label']}  Fmax={best['fmax_mhz']:.1f} MHz  mul_critical={best['mul_critical']}")
    print(f"  start: {best.get('crit_start')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
