///////////////////////////////////////////////////////////////////////////////
//     Copyright (c) 2025 Siliscale Consulting, LLC
//     Licensed under the Apache License, Version 2.0 (the "License");
///////////////////////////////////////////////////////////////////////////////
// PD-only wrapper: RISC-V core_top + gemm_top. Memories stay off-chip IOs.

`ifndef GLOBAL_SVH
`include "global.svh"
`endif

`ifndef AXI4_SVH
`include "axi4.svh"
`endif

module core_gemm_top (
    input logic            clk,
    input logic            rstn,
    input logic [XLEN-1:0] reset_vector,

    output logic [       INSTR_MEM_ADDR_WIDTH-1:0] instr_mem_addr,
    output logic                                   instr_mem_addr_valid,
    output logic [        INSTR_MEM_TAG_WIDTH-1:0] instr_mem_tag_out,
    input  logic [INSTR_MEM_WIDTH*ISSUE_WIDTH-1:0] instr_mem_rdata,
    input  logic                                   instr_mem_rdata_valid,
    input  logic [        INSTR_MEM_TAG_WIDTH-1:0] instr_mem_tag_in,

    output logic [XLEN-1:0] dccm_raddr     [LSU_DCCM_PORT_COUNT-1:0],
    output logic            dccm_rvalid_in [LSU_DCCM_PORT_COUNT-1:0],
    input  logic [XLEN-1:0] dccm_rdata     [LSU_DCCM_PORT_COUNT-1:0],
    input  logic            dccm_rvalid_out[LSU_DCCM_PORT_COUNT-1:0],
    output logic [XLEN-1:0] dccm_waddr     [LSU_DCCM_PORT_COUNT-1:0],
    output logic            dccm_wen       [LSU_DCCM_PORT_COUNT-1:0],
    output logic [XLEN-1:0] dccm_wdata     [LSU_DCCM_PORT_COUNT-1:0],
    output logic [     3:0] dccm_wstrb     [LSU_DCCM_PORT_COUNT-1:0],

    output logic              v_dccm_req,
    output logic              v_dccm_wen,
    output logic [      31:0] v_dccm_addr,
    output logic [     127:0] v_dccm_wdata,
    output logic [      15:0] v_dccm_wstrb,
    input  logic [     127:0] v_dccm_rdata,
    input  logic              v_dccm_rvalid,

    input  logic [AXI_ADDR_WIDTH-1:0] s_axil_awaddr,
    input  logic                      s_axil_awvalid,
    output logic                      s_axil_awready,
    input  logic [AXI_DATA_WIDTH-1:0] s_axil_wdata,
    input  logic [AXI_STRB_WIDTH-1:0] s_axil_wstrb,
    input  logic                      s_axil_wvalid,
    output logic                      s_axil_wready,
    output logic [AXI_RESP_WIDTH-1:0] s_axil_bresp,
    output logic                      s_axil_bvalid,
    input  logic                      s_axil_bready,
    input  logic [AXI_ADDR_WIDTH-1:0] s_axil_araddr,
    input  logic                      s_axil_arvalid,
    output logic                      s_axil_arready,
    output logic [AXI_DATA_WIDTH-1:0] s_axil_rdata,
    output logic [AXI_RESP_WIDTH-1:0] s_axil_rresp,
    output logic                      s_axil_rvalid,
    input  logic                      s_axil_rready,

    output logic gemm_busy,
    output logic pe_valid,
    output logic dma_arvalid,
    output logic dma_awvalid,
    output logic status_done,

    output logic [   AXI_ID_WIDTH-1:0] m0_axi_arid,
    output logic [ AXI_ADDR_WIDTH-1:0] m0_axi_araddr,
    output logic [   AXI_LEN_WIDTH-1:0] m0_axi_arlen,
    output logic [  AXI_SIZE_WIDTH-1:0] m0_axi_arsize,
    output logic [ AXI_BURST_WIDTH-1:0] m0_axi_arburst,
    output logic                        m0_axi_arvalid,
    input  logic                        m0_axi_arready,
    input  logic [   AXI_ID_WIDTH-1:0] m0_axi_rid,
    input  logic [AXI_DATA_WIDTH-1:0]  m0_axi_rdata,
    input  logic [ AXI_RESP_WIDTH-1:0] m0_axi_rresp,
    input  logic                        m0_axi_rlast,
    input  logic                        m0_axi_rvalid,
    output logic                        m0_axi_rready,
    output logic [   AXI_ID_WIDTH-1:0] m0_axi_awid,
    output logic [ AXI_ADDR_WIDTH-1:0] m0_axi_awaddr,
    output logic [   AXI_LEN_WIDTH-1:0] m0_axi_awlen,
    output logic [  AXI_SIZE_WIDTH-1:0] m0_axi_awsize,
    output logic [ AXI_BURST_WIDTH-1:0] m0_axi_awburst,
    output logic                        m0_axi_awvalid,
    input  logic                        m0_axi_awready,
    output logic [AXI_DATA_WIDTH-1:0]  m0_axi_wdata,
    output logic [AXI_STRB_WIDTH-1:0]  m0_axi_wstrb,
    output logic                        m0_axi_wlast,
    output logic                        m0_axi_wvalid,
    input  logic                        m0_axi_wready,
    input  logic [   AXI_ID_WIDTH-1:0] m0_axi_bid,
    input  logic [ AXI_RESP_WIDTH-1:0] m0_axi_bresp,
    input  logic                        m0_axi_bvalid,
    output logic                        m0_axi_bready,

    output logic [   AXI_ID_WIDTH-1:0] m1_axi_arid,
    output logic [ AXI_ADDR_WIDTH-1:0] m1_axi_araddr,
    output logic [   AXI_LEN_WIDTH-1:0] m1_axi_arlen,
    output logic [  AXI_SIZE_WIDTH-1:0] m1_axi_arsize,
    output logic [ AXI_BURST_WIDTH-1:0] m1_axi_arburst,
    output logic                        m1_axi_arvalid,
    input  logic                        m1_axi_arready,
    input  logic [   AXI_ID_WIDTH-1:0] m1_axi_rid,
    input  logic [AXI_DATA_WIDTH-1:0]  m1_axi_rdata,
    input  logic [ AXI_RESP_WIDTH-1:0] m1_axi_rresp,
    input  logic                        m1_axi_rlast,
    input  logic                        m1_axi_rvalid,
    output logic                        m1_axi_rready,
    output logic [   AXI_ID_WIDTH-1:0] m1_axi_awid,
    output logic [ AXI_ADDR_WIDTH-1:0] m1_axi_awaddr,
    output logic [   AXI_LEN_WIDTH-1:0] m1_axi_awlen,
    output logic [  AXI_SIZE_WIDTH-1:0] m1_axi_awsize,
    output logic [ AXI_BURST_WIDTH-1:0] m1_axi_awburst,
    output logic                        m1_axi_awvalid,
    input  logic                        m1_axi_awready,
    output logic [AXI_DATA_WIDTH-1:0]  m1_axi_wdata,
    output logic [AXI_STRB_WIDTH-1:0]  m1_axi_wstrb,
    output logic                        m1_axi_wlast,
    output logic                        m1_axi_wvalid,
    input  logic                        m1_axi_wready,
    input  logic [   AXI_ID_WIDTH-1:0] m1_axi_bid,
    input  logic [ AXI_RESP_WIDTH-1:0] m1_axi_bresp,
    input  logic                        m1_axi_bvalid,
    output logic                        m1_axi_bready
);

  logic accel_hold;

  (* keep_hierarchy = "yes" *)
  core_top u_core (
      .clk                  (clk),
      .rstn                 (rstn),
      .reset_vector         (reset_vector),
      .instr_mem_addr       (instr_mem_addr),
      .instr_mem_addr_valid (instr_mem_addr_valid),
      .instr_mem_tag_out    (instr_mem_tag_out),
      .instr_mem_rdata      (instr_mem_rdata),
      .instr_mem_rdata_valid(instr_mem_rdata_valid),
      .instr_mem_tag_in     (instr_mem_tag_in),
      .dccm_raddr           (dccm_raddr),
      .dccm_rvalid_in       (dccm_rvalid_in),
      .dccm_rdata           (dccm_rdata),
      .dccm_rvalid_out      (dccm_rvalid_out),
      .dccm_waddr           (dccm_waddr),
      .dccm_wen             (dccm_wen),
      .dccm_wdata           (dccm_wdata),
      .dccm_wstrb           (dccm_wstrb),
      .accel_hold           (accel_hold),
      .v_dccm_req           (v_dccm_req),
      .v_dccm_wen           (v_dccm_wen),
      .v_dccm_addr          (v_dccm_addr),
      .v_dccm_wdata         (v_dccm_wdata),
      .v_dccm_wstrb         (v_dccm_wstrb),
      .v_dccm_rdata         (v_dccm_rdata),
      .v_dccm_rvalid        (v_dccm_rvalid)
  );

  (* keep_hierarchy = "yes" *)
  gemm_top u_gemm (
      .clk            (clk),
      .rstn           (rstn),
      .s_axil_awaddr  (s_axil_awaddr),
      .s_axil_awvalid (s_axil_awvalid),
      .s_axil_awready (s_axil_awready),
      .s_axil_wdata   (s_axil_wdata),
      .s_axil_wstrb   (s_axil_wstrb),
      .s_axil_wvalid  (s_axil_wvalid),
      .s_axil_wready  (s_axil_wready),
      .s_axil_bresp   (s_axil_bresp),
      .s_axil_bvalid  (s_axil_bvalid),
      .s_axil_bready  (s_axil_bready),
      .s_axil_araddr  (s_axil_araddr),
      .s_axil_arvalid (s_axil_arvalid),
      .s_axil_arready (s_axil_arready),
      .s_axil_rdata   (s_axil_rdata),
      .s_axil_rresp   (s_axil_rresp),
      .s_axil_rvalid  (s_axil_rvalid),
      .s_axil_rready  (s_axil_rready),
      .accel_hold     (accel_hold),
      .gemm_busy      (gemm_busy),
      .pe_valid       (pe_valid),
      .dma_arvalid    (dma_arvalid),
      .dma_awvalid    (dma_awvalid),
      .status_done    (status_done),
      .m0_axi_arid    (m0_axi_arid),
      .m0_axi_araddr  (m0_axi_araddr),
      .m0_axi_arlen   (m0_axi_arlen),
      .m0_axi_arsize  (m0_axi_arsize),
      .m0_axi_arburst (m0_axi_arburst),
      .m0_axi_arvalid (m0_axi_arvalid),
      .m0_axi_arready (m0_axi_arready),
      .m0_axi_rid     (m0_axi_rid),
      .m0_axi_rdata   (m0_axi_rdata),
      .m0_axi_rresp   (m0_axi_rresp),
      .m0_axi_rlast   (m0_axi_rlast),
      .m0_axi_rvalid  (m0_axi_rvalid),
      .m0_axi_rready  (m0_axi_rready),
      .m0_axi_awid    (m0_axi_awid),
      .m0_axi_awaddr  (m0_axi_awaddr),
      .m0_axi_awlen   (m0_axi_awlen),
      .m0_axi_awsize  (m0_axi_awsize),
      .m0_axi_awburst (m0_axi_awburst),
      .m0_axi_awvalid (m0_axi_awvalid),
      .m0_axi_awready (m0_axi_awready),
      .m0_axi_wdata   (m0_axi_wdata),
      .m0_axi_wstrb   (m0_axi_wstrb),
      .m0_axi_wlast   (m0_axi_wlast),
      .m0_axi_wvalid  (m0_axi_wvalid),
      .m0_axi_wready  (m0_axi_wready),
      .m0_axi_bid     (m0_axi_bid),
      .m0_axi_bresp   (m0_axi_bresp),
      .m0_axi_bvalid  (m0_axi_bvalid),
      .m0_axi_bready  (m0_axi_bready),
      .m1_axi_arid    (m1_axi_arid),
      .m1_axi_araddr  (m1_axi_araddr),
      .m1_axi_arlen   (m1_axi_arlen),
      .m1_axi_arsize  (m1_axi_arsize),
      .m1_axi_arburst (m1_axi_arburst),
      .m1_axi_arvalid (m1_axi_arvalid),
      .m1_axi_arready (m1_axi_arready),
      .m1_axi_rid     (m1_axi_rid),
      .m1_axi_rdata   (m1_axi_rdata),
      .m1_axi_rresp   (m1_axi_rresp),
      .m1_axi_rlast   (m1_axi_rlast),
      .m1_axi_rvalid  (m1_axi_rvalid),
      .m1_axi_rready  (m1_axi_rready),
      .m1_axi_awid    (m1_axi_awid),
      .m1_axi_awaddr  (m1_axi_awaddr),
      .m1_axi_awlen   (m1_axi_awlen),
      .m1_axi_awsize  (m1_axi_awsize),
      .m1_axi_awburst (m1_axi_awburst),
      .m1_axi_awvalid (m1_axi_awvalid),
      .m1_axi_awready (m1_axi_awready),
      .m1_axi_wdata   (m1_axi_wdata),
      .m1_axi_wstrb   (m1_axi_wstrb),
      .m1_axi_wlast   (m1_axi_wlast),
      .m1_axi_wvalid  (m1_axi_wvalid),
      .m1_axi_wready  (m1_axi_wready),
      .m1_axi_bid     (m1_axi_bid),
      .m1_axi_bresp   (m1_axi_bresp),
      .m1_axi_bvalid  (m1_axi_bvalid),
      .m1_axi_bready  (m1_axi_bready)
  );

endmodule
